### ISSUE TITLE
Old minutes appearing on new meetings

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#103]
I cloned the Aug 31 meeting to create an agenda for Sep 15. I found that the minutes, (eg of the Weaver training item) got cloned, too. I am trying to prepare the agenda for today's meeting and can't figure out how to ditch the minutes from last time.

**Comment by agilepro** [comment]
Here is what happened:  you cloned the Aug 31 meeting, and forgot to set the date for the new meeting.  This will default to Sept 6.  The minutes were made after the meeting, and any minutes objects from within 7 days is displayed.  Setting the meeting date to Sept 15 solved the problem about having the minutes in there.  

The minutes you see are ONLY minutes on agenda items that are linked to discussion topics.  This is actually a feature that on the discussion topic you can see the minutes for all the meetings that have occurred.  The problem is: how to associate minutes with a particular meeting?  Hmmm.  Maybe another setting is needed that associated this.  That would not be too difficult...

**Comment by agilepro** [comment]
I have a new idea to allow you to set the "window" that is exposed in the meeting. It is not too hard so hoping to look at doing this soon.

**Comment by agilepro** [comment]
This behavior has been changed/removed.  Minutes are now concrete objects on the agenda item.
