### ISSUE TITLE
Home page need alerts & reports

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#11]
When a user goes to their home page they should be shown or given the option to look at their Weaver action items or activity since last visited.  Readily answering many common questions:
1.  Is there anything needing my response: proposal consents; decision text consents; feedback requests; votes; new topics or new comments to topics to review; etc.
2.  Are there any workflows in limbo where I might step in as facilitator to move them along?
3.  Am I in facilitator role on any workflows?  What timer is in effect?  Who has responded and who has not?  Can I override the timer and move things into the next step? Etc.
4.  Any new decisions made?  In my circle?  In other circles?
5.  Any new proposals made?
6.  Any changes to policy doc since I last looked at it?
7.  Etc.

**Comment by agilepro** [comment]
Very frustrating.
1. The list of action items assigned to YOU is available.  Called "Goals" and it appears on every page.  I have changed this (will appear soon) to be "To Do" but it is the same functionality.
2. "Workflows in limbo" is a very arbitrary expression.  There are workitems assigned to people.  I have just added a list of proposals that YOU have not responded to, in order to remind users of that action that is needed.  But thsi statement (2) seems to be about "third party" workflows that you might "step into" and I really don't know what you want other than the readily apparent information about workflows and their current state.
3. I am not sure what a facilitator in a workflow is.  Please define workflow including all the specific steps.
4. How would the system know if there are any decisions to be made?  Are you in the habit of writing down "decisions that might be made?"  I am not aware that anyone works in the fashion of marking down decisions that they plan to make in the future.
5. there IS a new list of proposal that YOU have not responded to.  Will be on the server soon. 
6. There IS a mechanism to show changes to a worspace:  all the new topics, all the new documents, etc.  However, policy document is not specifically modeled.  If the policy document was a document, then YES there is a notification that the document has changed.
7. Etc.  Really? Vague unspecific statements don't move the work forward.  Are we supposed to read your mind?  If you have a specific change you have thought through,and would like to see, I am all ears.  But merely suggesting that there are other things that you have not really taken the time to specify does not actually help anything.

**Comment by goodgeyes** [comment]
~ 03 Dec I created a Google Doc titled:  **Joe's proposed simpler decision chunk solution**(https://docs.google.com/document/d/1vX99g9V4NnEKlrrlut_G5moBxXqStLZ7KnmfLJJQrz8/edit?usp=sharing)  This was a first draft attempt to relay to the whole team the workflow process of taking an idea all the way thru to a formalized decision logged in a decision tree.  This is the type of very detailed step-by-step process I have been referencing.  Sorry, apparently the reference has been lost in other's minds.

I'm happy to address all your new questions, but I'm not 100% sure where and how you prefer to do this.  Do you want to stay in GitHub or do we want to move all this process stuff back over in Weaver?  I earlier saw both Ian & Keith agree all the process stuff should be moved over to Weaver, but yet the discussion has continued here.  

I'm going to shift process discussion back to a Weaver topic.  Hereafter leave GitHub for only coding bugs and issues.

**Comment by agilepro** [comment]
This is a larger design discussion that effects the way that all parts of the system interact.  This is best held on the discussion topics or meetings.  So closing here.
