### ISSUE TITLE
adding a member

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#112]
I just added Gopi Muvva as member of the Weaver Tutorials folder. However, when he goes to it, he gets a message that he is not a member. How long is the delay for him to get access? If it is a built in delay, would be helpful to have a note saying how long the delay may be.

**Comment by agilepro** [comment]
There is no delay, literally no delay.  I believe the problem here was either a typo or some other difference in the email address entered.  Other issues here point to a duplicate entry, and that might have simply been an uppercase/lowercase difference.  Updated the software to detect and correct that problem.  Hope that is it, but if it happens again let me know.
