### ISSUE TITLE
need to fade out after invite

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#122]
After clicking on the name of a new workspace member, I get the wizard that includes the option to Invite. I click on the Invite but then the box does go away. I'm not sure if it took the click. I just ended up sending an invite email twice. Could we make the wizard box go away after clicking invite? Why do we need a separate box to ask if I want to send the invite? Just clicking invite seems like it should be enough. Anyway, when the second box goes away, the wizard that shows Invite is still there. I enter a new name and it is still there. I click on the new name and the old wizard goes away and then I have to click again on the name to get a new wizard for invite.

Yike. After I wrote the above, I tried adding another name but this time I had to click on Invite twice to get the "do you want to send the invitation message" and then I had to click the invitation message twice to get it to go away. I am over the Atlantic on airplane wifi. So, I could be suffering from lowbandwidthitis.

Also, the Save Changes button makes such a subtle change when I click it that I click it a couple of times because I'm not sure the click took. Would appreciate some clearer feedback that the click actually took.

A small point: to get to the Save Changes Button, I have to scroll down. that's a minor hassle and when I don't see the button, it's easy to forget about it. Request to have the Save Changes button visible when you are adding someone.

**Comment by agilepro** [comment]
With the nav list in the left, the area remaining for a double column format is just too small.

I reformulated it:
1) The edit is a pop-up modal.  This makes it far clearer that you have to save.
2) since it is full width of the window, it does not extend as long as it did, making button more accessible
3) Display the description on the main screen
4) turn the circle icons into menus
4a) Launch the invite directly from the circle icon ... instead of the input box
4b) access profile from the icons, not the input.

As for the delays, that must be the network delays.  The dialog box closes close to immediately.  The email is sent asynchronously, and that will pop up a notification a few moments (or maybe a minute) later saying that the email is completely sent.  

If you click the invite option twice, I found it can pop up two dialog boxes on top of each other, and then you will have to close both of them.

Also, you may have been having problems with duplicate entries, particularly when the same email is in, but one has an uppercase letter where the other has a lowercase.  In some cases that was allowed, and it caused problems.  

I am hoping that the new changes addresses all this.
