### ISSUE TITLE
got a shut down suddenly

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#126]
I'm still on my airplane heading home. Have been working on the Weaver Tutorials workspace trying to add people from Pune and then got a freeze. When I renewed the screen got the message below. Other websites are working ok.

![image](https://cloud.githubusercontent.com/assets/10082365/20031284/4ad4a512-a375-11e6-83ee-5f742af8efac.png)

**Comment by agilepro** [comment]
What is happening here is that your network is serving up a DIFFERENT page than the one from the server.  Generally, this happens when the network is interrupting a HTTP request, and presenting a page prompting to authenticate yourself to the network, or accept the condition of using the network.

Unfortunately, networks do this even when HTTPS is being used.  Under HTTPS, the problem is that the certificate is not valid for the content that the network is giving you.  This is precisely the point of HTTPS in the first place is to prevent companies from reading or altering the content that you are requesting.

This is, then, correct behavior.  If you ever see this again, please try  accessing ANY OTHER HTTPS website (like gmail, or many others).  If you get the same error, you know that the problem is the network you are trying to use.

Access a website that does NOT use HTTPS, and you will get the prompt, and probably enable network access again.
