### ISSUE TITLE
what happened to my phase comment?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#142]
I created a new topic (Can Weaver Replace Email Strings?) and chose Picture Forming as my mode.

I wanted to give some facilitation instructions, so in the Picture Forming entry that appeared, I pulled down "Edit your comment" and entered a comment I then saw that this comment did not appear. I finally figured out that blank was the default and I had to pick Comment before my comment would appear. My recommendation is to simply give one option: Comment. Have it default to comment. Proposal, Round, and Minutes are simply not applicable to the facilitation section divider. It should only allow facilitation comments (and comments on those comments).

**Comment by agilepro** [comment]
Very good point.  The edit and delete menu appeared at the time that I made it more liberal about allowing you to delete at any time.  The state model between all the comments and all the menu options is a bit too complex.  However, I have changed the style so that no menu pull-down appears at all for the phase change comments ... in fact they now appear completely different from comments and that should help make them appear distinct.
