### ISSUE TITLE
User confusion when same comment appears in two meetings

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#156]
Keith's comment in the UI item of the Feb 16 meeting about ManageHub's software got cloned to the Feb 22 meeting but I can't delete it from there- is no longer relevant & won't go away

**Comment by agilepro** [comment]
Here is what the issue is:
A meeting agenda item is linked to a discussion item.  The discussion item has comments on it.  Those comments appear in the meeting.  Comments from a week before the meeting to a week after the meeting are included.

The comments made on Feb 16 are less than a week away from the Feb 22 meeting, so you see them.

Is the comment no longer relevant?  The comment was made on Feb 16.  Generally we keep old comments forever -- comments never become out of relevance.

John was worried that the inappropriate comment was included in the meeting, but I think he thought it was a copy of the original.  Instead it is just the same comment appearing in two places.  I think this may always  be a problem with discussion topics linked as meeting items.  I don't know what we can do to make this clearer.

Maybe a two column mode?  Showing the meeting on left, and discussion topic on the right?

**Comment by agilepro** [comment]
this has been eliminated.  Topics do not overlap agenda items.  They are separate
