### ISSUE TITLE
problem with creating new workspace

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#162]
I tried to create a new workspace this evening and got this screen. Was unable to create the workspace.
![image](https://cloud.githubusercontent.com/assets/10082365/23757069/c425505e-050b-11e7-8df8-53e55ab0c553.png)

**Comment by agilepro** [comment]
We had a number of problems this week, and I believe it is all due to some problems with the User Profile XML file.  I believe that the code managing this is not thread safe and now that we have more users a problem has appeared.   Several times I had to restart the serve and refresh all the User Profile information into memory.  Yesterday I rewrote the User Profile management code to be completely safe for muti-thread interactions.  I am hoping this addresses all these problems.  Should be available Monday.
