### ISSUE TITLE
absolute links needed in email

### ISSUE THREAD

**Issue by agilepro** [agilepro/cognoscenti#164]
When you put a link in a comment to a topic in Weaver, it saves the RELATIVE URL to that thing, but that needs to be converted to an absolute URL when sent in the emails.

**Comment by agilepro** [comment]
OK, it two 2 hours, but found and fixed that problem!

**Comment by johnabuck** [comment]
On the description of the meeting, I had used one zoom number for the meeting. I was asked to change it to another number. So I highlighted the old number and pasted in a the new number. However, the link actually sent everyone to the old address despite saying the new address. See the video of the meeting - is in the first 10 minutes. We can probably recreate scenario since both meetings are intact

**Comment by agilepro** [comment]
The appropriate thing to do is to delete the entire link, and add a new one.

The problem is that a link has two pieces of data: the address and the text.  It is very convenient to be able to modify the text without the address, since they usually are different.  

when you type something starting with http we ADD a link in for you, but you still can edit the text, without editing the address.

One possibility is to remove the automatic conversion to link.  This is done when SAVING.  It might be done while displaying, but you display 20 to 100 times more frequently than you save.
