### ISSUE TITLE
decisions

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#172]
As an experiment, suggest put in an option in the minutes box to log the content as a decision. if you modify, update the decision and don't create a separate decision. Discussion: we would want to decouple the two if we want to have a "pure" decision (not any accompanying notes). 

An afterthought: maybe that is the function of the comments box: taking notes without the intent of recording them in the formal system. The minutes won't show the informal notes but they could be recovered by going back to the original meeting record.

**Comment by agilepro** [comment]
What I have done is to allow you to "create a decision" from any kind of comment, proposal, round, or minutes.  It pops up the create decision and places the text from the current comment in there for editing.  Then you clean it up, and post as a decision.  You can do this multiple times if a particular comment or minutes has more than one decision in it. 

I would make the case, that when taking notes on a meeting, or making a comment on a discussion, that the exact content of those notes is NEVER suitable for entry in the decision list.  Of course it is possible, but I consider it unlikely.  When taking notes the typing is done with a different attitude.  A comment is often to persuade.  Minutes are designed to capture a lot of things that happened around the discussion of the decision.  None of that should be in the decision, which should be crafted as a succinct and clear statement.  Comments and minutes notes are almost never crafted to succinct and clear in that way.  The effort of writing a good decision is quite a bit more than writing a comment or minutes.  

What we can do, is review all of the editing meetings, and get a feeling for how often the minute entries or the comment entries would make a good "decision" without editing.  Go look at them now.  I think you will find that there is not a single comment or minutes notes that would be suitable as a decision without editing.

You seem to be worried that after you craft the decision, you might want to change it.  How often does that happen?  You seem to be worried that there will be two copies of record that have to be changed.  If so, I recommend that you use the link from the decision to the comment, and from the comment to the link, and don't duplicate.

**Comment by agilepro** [comment]
I believe this is arguing for the elimination of "duplication".  The idea is: I write a decision once, and it appears in several places, and it is kept in sync.  I believe this is a common mistake thinking "I want one clear representation of the world, and everything should be in one place, and that will minimize the work involved." 

The problem is, that as you write a comment, the audience for that comment is one thing.  Later, if people have come on board, you write a decision, and that decision is written for a very different audience.  It is very unlikely that someone will write a comment, or make a "minutes" entry, and that become verbatim a decision.

Instead, comments record generally not just the decision, but a lot of supporting evidence for the idea that the decision makes sense.  You need to have that extra supporting material.  Others will argue back.  But when you write the decision, you want to make it as succinct as possible.  You want to refer to the supporting argumentation, but you don't want that included IN PLACE.

What about when you CHANGE a decision.  Wouldn't it be nice it that change would re-write all the discussion that happened before?  It woudl, but it can't.  The fact is that the discussion happened before, and that is history.
