### ISSUE TITLE
access title and header

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#177]
In setting up today's meeting the clone-to-draft sequence worked well. However, I was then unable to access the header / title area to change the title of the meeting.

![image](https://cloud.githubusercontent.com/assets/10082365/25711898/125c19f0-30be-11e7-9d43-303bbaae24ca.png)

**Comment by johnabuck** [comment]
Nevermind - finally noticed small edit symbol on right side. Can the edit symbol be put nearer to the part of the heading that will be edited? Would make a stronger visual connection.

**Comment by agilepro** [comment]
OK, it is normal when the UI is changed from what you are used to, it is initially hard to see where things have changed to.

Making the edit icons closer also has the effect of cluttering information with control symbols.   Of course, you can make them closer if you make your browser window narrower.

We should talk again when you get used to this.  I think you will find that because of the horizontal lines, the association with what is being edited is quite strong.  If it remains clumsy we should discuss after we have some experience.
