### ISSUE TITLE
other user interface items

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#195]
The following comments come from teaching someone today how to do circle admin function.
1. the box for title of the item is too small - especially if the title is long
2. to change the time of an item it would be nice to just click on the time and not have to open a list, find item setting, find the duration box, then change. - i.e., fewer clicks.
3. The reminder is in minutes. Wants to send a reminder a few days beforehand
4. I would like to have the whole agenda in one document so that I could paste it into a calendar reminder.

**Comment by agilepro** [comment]
1. new agenda item is done through pop up box, and space for title is bigger
2. everything is in the pop up box.  The problem is that it we make it TOO easy, then everyone is accidentally getting into the edit box when they don't really want to.  There is a tradeoff.  Happy to entertain suggestions, but making it one click is going to make it one click for everyone  -- unless we implement different roles of interaction and that introduces more complecity.

**Comment by agilepro** [comment]
1. agenda item name box shows 50 letters, and that is a pretty long title.   Longer titles are possible by scrolling, but for a number of reasons should be discouraged.   A title should be no more than a few words, the rest should be in the description.

2. click on time opens the dialog box now.

3. reminder can be in days

4. entire meeting is available as a single HTML using the "Show Flat" display option.
