### ISSUE TITLE
language refinement

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#218]
I noticed in preparing our next Weaver meeting that in the meeting header "Members" is a confusing term because it does not in any way connote that I go there to set the time of the meeting and reminder. Since there is plenty of space, suggest that the main display say something like: "Members/Meeting Date & Reminder".

Actually, as I look at it the edit boxes for both Scheduled Time and Target Roles are identical. Perhaps we should eliminate one of them? However, having a target role makes sense except that there is no way to add guest addresses that don't have a role. Or if one creates a "Guest" role, there is not way to have multiple roles like "Members", "Guests"

**Comment by agilepro** [comment]
I have added a few line is display to make it clearer what is happening

**Comment by agilepro** [comment]
It seems to me, that you had the "intent" to edit the email reminder period, but since reminder period does not appear at that level, you had to click the edit button for "Target Role".   The value of target role is "Members" and you were seeing that as the somewhat confusing title.

Here is what I have done:  I have made a entry in the table for "Scheduled" time.  That brings up the same edit capability for all the meeting values except description which is different.

![image](https://user-images.githubusercontent.com/5544889/29789603-6dbc887e-8beb-11e7-97c6-ea474e1216ae.png)

It is generally viewed as acceptable to have redundant controls that get you the same place.  The point is that if you want to edit the reminder schedule, click on the edit there.  If you want to edit the target role, click on the edit icon there.  They both go the same place, but that doesn't matter:  regardless, you get to the screen that allows you to edit the value you wanted to edit.
