### ISSUE TITLE
UI test of a meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#233]
See recording of meeting today: https://zoom.us/recording/play/ruMVVIOG3--OWRtpHwEHgucVG3Bik5lN1p2Pfzkg3jFs8bZqG3LhO3bLQiFJU03y.

In the first 20 minutes, Kester makes several suggestions regarding layout of the screen - eg, be able to open an agenda item by double clicking on it rather than having to do a pull down. Having action items be directly accessible so that anyone can fill it out. In the screen sharing starting that starts around minute 14:35 you can see some display problems, particularly with the timers. After that the meeting runs more smoothly.

**Comment by agilepro** [comment]
Suggestions:

(1) double click on title instead of pull down to edit agenda item
(2) error when deleting agenda item ... something about no role found.  Role was "Certification mentoring" -- that was probably a configuration error.  Should test by setting up a meeting on an unusual role, ***  I made a change
(3) timer was not "synched" because the meeting page needs to be refreshed to see the current timer.
(4) Action steps could be more seamless.  Maybe a small window for new action items.

**Comment by agilepro** [comment]
probably all fixed
