### ISSUE TITLE
s06 error messages

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#236]
i keep getting theses error messages popping up even when not in weaver

![image](https://user-images.githubusercontent.com/10082365/31685990-f8624368-b352-11e7-83fb-04f5046650d8.png)

**Comment by agilepro** [comment]
Please confirm for me that these happen when you have an window open in your browser, and then you put the laptop to sleep or otherwise disconnect from the internet for a while?

I believe there is something about waking up a browser after being offline causes these errors as it attempts to reinitialize the page.

**Comment by agilepro** [comment]
It turns out it is harmless.  This was part of the "autologin" which happens every 25 minutes or so, and when you had the laptop in sleep mode, generally it would run first thing when you unsleep it. 

I have changed this so that it no longer pops up the window asking the question.
