### ISSUE TITLE
Emails from rounds/proposals should show choice

### ISSUE THREAD

**Issue by rgilman** [agilepro/cognoscenti#24]
I just noticed that in the emails from "Minutes for Meeting: Catching Up!: Quick round response" where both Keith and I consented without making a comment, those consents don't show in the email. I suggest that the choice, when there is one, (in this case "consent") be prepended to the comment, perhaps like: Consent - [whatever the comment is if there is one]

If there is no comment it could just be "Consent" (or whatever the choice).

**Comment by agilepro** [comment]
yeah, that is a bug.  "proposals" are supposed to have a slightly different heading than "rounds" but it appears they both get the heading for "rounds" (which don't have a choice).

The choice has been located above horizontal line for the response.  I think I am going to move to to be below the line so it is clearly part of the response, and so that when they enter nothing else, it clearly make the choice part of the response.

**Comment by agilepro** [comment]
The new "templates" for these emails have the choice clearly in view now.
