### ISSUE TITLE
possible email glitch

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#254]
when created a comment in a topic a few minutes ago, I chose "Email" from the lefthand bar and chose the Email Prepared option. I got this message:
![image](https://user-images.githubusercontent.com/10082365/46513153-4d3d2c80-c825-11e8-8577-e03ec1545aa3.png)
Nothing showed up in Email Sent. A few moments later it showed up in Email Sent. I checked the Email Prepared choice again and this time the error message did not appear and it only showed sent emails.

**Comment by agilepro** [comment]
I know the cause of this error, and I have included a fix that avoids the direct problem.  However, I don't know how to reproduce the problem exactly.  It appears to be timing related:  accessing the email list during a narrow window between when the record is created and when it is sent.  

I am going to mark this as fixed, because the exact stack trace will never happen again.   But if anything similar to this happens let me know.
