### ISSUE TITLE
son of safety message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#275]
I logged out of Weaver and closed the tab and reloaded and signed in again. No more nasty security messages but the URL still shows Not Secure:

![image](https://user-images.githubusercontent.com/10082365/48043370-538c3480-e154-11e8-86e5-0604d8bb7fce.png)

**Comment by johnabuck** [comment]
just opened another instance of Weaver. No problem with second instance. No change in URL Not Secure message for first instance

**Comment by agilepro** [comment]
I believe this is fixed.   I don't understand the problem, since I updated the security certificate before it was needed.  Still somehow you got a wrong certificate.   

MAYBE, you had retrieved the certificate a few days earlier, and then when it expired you still had the expired certificate in cache?   I don't know but if it happens again let me know.
