### ISSUE TITLE
another topics problem

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#277]
I tried to reply to a topics discussion string inthe Facilitation class, I clicked Save & Post but the message screen still lingered. Clicking Save & Close would not remove it - couldn't close & so just got off the screen:

![image](https://user-images.githubusercontent.com/10082365/48989749-a163df00-f0f9-11e8-8345-9a8e1b1fb5f6.png)

**Comment by johnabuck** [comment]
Also, when I came back onto the screen, it looked like the Save & Post had not worked because my message did not appear

**Comment by agilepro** [comment]
This would be explained by the problem I fixed today.  If the ONLY thing you did was add a comment, then it is possible that comment did not get saved.  The auto refresh would then get a version without the comment.  Any attempt to save edits would be rejected because it is trying to update a comment which does not appear in the page.  This would happen when you took a long time to create a comment.
