### ISSUE TITLE
Problem with round

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#281]
John encountered problem of inserting a Round but being unable to save & close the comment box. We also duplicated similar results with simultaneous typing. Is a conflict caused by multiple users saving at the same time.

**Comment by agilepro** [comment]
The problem was a cache problem combined with multi-user concurrent editing.  I have checked in a fix today, and I can successfully edit round results with different people editing in as many combinations and timings as I can think of.   It should be safe for anyone to edit any comment or any response to a proposal/round.
