### ISSUE TITLE
note from Eduardo about sign up process

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#282]
Eduardo Toledo | Eduardo Toledo | Dec 13, 2018, 6:27 PM (23 hours ago) |   |  
Hi, John, i have some feedback. Finally, I sent out invitations to participate and join the group. When people receive the invitation message, and accept the invitation, they cannot directly enter the tool, but the person who sent the invitation must accept it. Why not enter directly? If I have sent an invitation, it is for that person to participate in the group. I don't think it's necessary to reauthorize or deny access. Also, if they receive the invitation and want to enter it is because they are interested in that moment. If they have to wait for the invitation, the interest of that moment is lost. I think allowing instant access to whoever receives an invitation improves usability. Several people told me that. That's my main feedback, otherwise, I'm delighted with the tool. 

I replied:
Thanks, Eduardo. Great feedback. 
Sign up is a balance between easy access and preventing robots. It's possible to give people you invite a code. I'll suggest to Keith that we provide that to site owners.
John

**Comment by agilepro** [comment]
The "Invite Users" works correctly.  However, the "Multi-person Invite" works just as Eduardo says.  That needs to be fixed.   Glad he mentioned it.

**Comment by agilepro** [comment]
John, I checked in a fix for this.   Please respond to Eduardo with this message:

Eduardo, thanks so much for pointing this out.  You are absolutely right that the person should not have to approve access after inviting, and very true that immediate access is a much nicer experience.  

The single person invite was working exactly that way.  What I had missed is that the multi-person invite was still using the old method which required confirmation.  I have updated this now, so if you invite a person, or even a long list of people, they will be entered automatically into the role, and they will be accepted immediately whenever they access it.  What is also nicer is the the multi person invite now uses the same history list showing who has already been invited, and whether they have accessed or not, so that it is easier to track who has been successful in arriving.

Thanks for pointing this out.  By working together we make the platform that we need to make our lives easier.
