### ISSUE TITLE
test of pasting being done with Florian

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#284]
I tried pasting a google doc into a Weaver Topics Comment. Paragraphing was fine but extra spacing got added. Original doc: 

![image](https://user-images.githubusercontent.com/10082365/50553374-8c87e780-0c73-11e9-88a7-43bc104a0762.png)

Here is what is looks like when I pasted it:

![image](https://user-images.githubusercontent.com/10082365/50553387-ae816a00-0c73-11e9-88c6-11db36ce878d.png)

**Comment by johnabuck** [comment]
Here is what it looks like when I pasted it:

![image](https://user-images.githubusercontent.com/10082365/50553399-f0aaab80-0c73-11e9-93bb-f038359caa83.png)

**Comment by agilepro** [comment]
That is correct. We do not preserve any formatting beyond what we offer in the editor.  We do not offer indentation, so all the paragraphs are at the left margin.  The headers seem to have been read correctly.   All of the text was transferred properly.

Looks like this is "correct"

**Comment by agilepro** [comment]
The "extra line" is simply because when formatting text, we ALWAYS leave white space between paragraphs.  There is no extra line there, it is just that the formatting is that between header and a paragraph -- same as between two paragraph -- we always leave some vertical white space.  

As far as I can see, in this example, the text was captured correctly, and styles (header/paragraph) were identified correctly, and so the paste worked correctly.   the "difference" is due simply to the formatting of that text for display.

I am going to close this, but feel free to re-open if you think there is still something to address.
