### ISSUE TITLE
Would like bulk add and invite function

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#33]
I just enrolled Nate Whitestone in a new workspace called Healthy Power Alliance (HPA). Here is user experience: 
1. First try: I thought I enrolled Nate, but nothing happened. Dont know how I screwed up.
2. Second try: I inadvertently created Nate's name as a new role. Again, don't know how I screwed up.
3. Third try: this time I succeeded in getting Nate enrolled as a user.
4. I wanted to send an invite to Nate. I puzzled over Keith's instructions and couldn't figure out what to do. Almost wrote a whinny "oh please help me" note to Keith. Finally figured out to display the Create New Role menu (title is what threw me I think) and then click on Nate's email address in the member list.
5. Request that we have a way of enrolling people in mass. E.g., if I go ahead an have the HPA people start using Weaver, I'll need to enroll upwards of 25 people - just for starters.

Despite the grousing, thank you, Keith, for all you are doing!!!!!!!!

**Comment by agilepro** [comment]
This is very good feedback.  Need to consider the usability of the roles page.  Right now the add user to role does the double duty of adding new email addresses, as well as adding existing users from a pick list.  Hard to say whether there should be two separate functions for that.  We certainly could make a special "Add Member" function which avoid the complexity of having to select the "Members" role.  If we know ahead of time that the person is likely to not have a profile, then getting a list of email addresses should work better than prompting on each one.  We could also combine the add and the invite in a single operation without much difficulty.   

Will consider an "Add and Invite" option that gets a message body and a list of email addresses in the same pop-up, and does all the work.

**Comment by agilepro** [comment]
I added a feature that when you add a person by email address, or you add a user that has never logged in, it will automatically prompt you to send an invite.  If the user has already logged in, then it does not prompt for this, because presumably they will find out normally by events, and because they don't need to set their password.

If you modify the message, then for each subsequent user you will get the same message so it is easy to add an address, send message, add address, send message, and so on.   While this is not really a "bulk" add, I really don't foresee more than 6 to 10 users being added by any one person, and this is easy for that range of users.
