### ISSUE TITLE
strange behavior entering multiple person action item from flat form

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#332]
entered names on flat form (notetaking form). got this:
![image](https://user-images.githubusercontent.com/10082365/53387588-89e4fe00-3955-11e9-9335-5d57b57fc44b.png)

**Comment by agilepro** [comment]
I believe now you will be able to paste a list of names anyplace you can set names,   In the string being pasted, you can separate email addresses by comma, semicolon, space, or newline.   Also, when typing you can end an email address with space or comma and it will immediately turn into a box.  Also, found the reason that spaces were being converted to hyphens.  You shouldn't see that now anyway since space terminates the current entry, but just listing it here as a fix.

There is no direct fix for left over entries of big long strings, however if you select that value it will be parsed into separate email addresses and individually considered, and any existing object when you edit it, if there are any left over multiple email user they will be automatically parsed and replaced with the separate tokens.   I think it will clean up all the existing problems.
