### ISSUE TITLE
problem again with signing up members of a workspace

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#338]
I am setting up a class and have 25 names in a comma delimited list. I want to enroll them in the workspace that will be for the class but I can't just copy in the list. I have to enter each name individually. This is a major pain in the touche!

**Comment by agilepro** [comment]
I believe now you will be able to paste a list of names anyplace you can set names,   In the string being pasted, you can separate email addresses by comma, semicolon, space, or newline.   Also, when typing you can end an email address with space or comma and it will immediately turn into a box.  Also, found the reason that spaces were being converted to hyphens.  You shouldn't see that now anyway since space terminates the current entry, but just listing it here as a fix.

There is no direct fix for left over entries of big long strings, however if you select that value it will be parsed into separate email addresses and individually considered, and any existing object when you edit it, if there are any left over multiple email user they will be automatically parsed and replaced with the separate tokens.   I think it will clean up all the existing problems.
