### ISSUE TITLE
Need a way to update documents when decisions that affect them are made

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#34]
I received the following suggestion for software that may already do what we need - mark up software.

Check out MySociety.org. They use markup software to develop legislation. (have not personally dug into this suggestion very far because am not sure what to look for.

**Comment by agilepro** [comment]
I spent some time, but see no clear description of this on the site.  I am going to close this here, because GitHub is for clear bugs and actionable problems with the current implementation.  Discussion of future possible features, or even new approaches to existing features, should be done on the Weaver site itself.
