### ISSUE TITLE
include a cc on invite messages

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#351]
To add to the Weaver backlog, I just had a situation where I wanted to cc someone on the "invite you to a workspace message" to let him know that I'd invited someone per his request. 
Two lessons to note: 
1. I couldn't cc him.
2. The person requesting me should have been able to do it himself. (I'm wondering if some sort of "show me" program would help this "dunno what to do next challenge,

**Comment by agilepro** [comment]
OK, this is a good idea.

But I also want to clarify some problems.  The invite email is a security thing, because it verifies the identity of the email.  The solution to this is that a *different* email could be sent, that does not have the security feature, just saying that the invite was sent.  It is not actually a CC, just an email notification.

Another option that should be done immediately is to generate a history event telling that it was done.  This become a permanent part of the workspace so that anyone can know that an invite was sent if they want to know it.

FINALLY: ANYONE who is a member of a role can invite other members!   IT seems that you did not know this, nor did the person who requested it.   Maybe that is a training issue as well.   ANYONE can request by themselves that someone else join.  This is unusual.  Most software requires that an "admin" do this, but we allow anyone to do it.  Can we capitalize on this more?

**Comment by agilepro** [comment]
Here is another point.   There is a clear list showing who was invited and when.   Why not just have them look at that list?   Isn't that a reasonable way to konw?

![image](https://user-images.githubusercontent.com/5544889/55604089-e8ef1d00-5722-11e9-8ffd-f895612d078a.png)
