### ISSUE TITLE
don't allow a workspace to be its own parent

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#372]
When I was coaching Mona Patrao today on using her Learnodai site, she accidently made the workspace called Learnodai Sociocracy and Induction Circle a parent of itself - rather than the general circle. I was unable to undo it. I made both you and me site executives so that you can see the problem. I'm unable to unscrew the mess. See
https://s06.circleweaver.com/weaver/t/edux/learnodai-sociocracy-and-induc/frontPage.htm. You can see that it's not possible to rename the parent as the Learnodai General Circle. This item is URGENT because she'd like to get going with organzing her site.

**Comment by agilepro** [comment]
That workspace was set up with ONLY one person as administrator:  Mona.  The reason you could not change it is because you were not administrator.

However Mona certainly could just change the parent to be something else.  I made myself administrator, and then changed the parent to be General Circle.  I don't understand why she had trouble doing this.

I could certainly exclude the current circle from the list of settable parents.  This won't prevent it, but it will make it far less likely.

**Comment by agilepro** [comment]
The current workspace is not in the list of selectable worspaces when setting the parent.   That should eliminate the largest part of the problem.
