### ISSUE TITLE
cant send notify invite

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#375]
I'm trying to let people in Notify roles about a meeting. I chose multi-user invite. I pasted in these addresses:
Christine Karavakis <ckaravakis@imagorelationships.org>, Sophie Slade <Slade.imago@icloud.com>, Ian Tomlinson <iant241@gmail.com>, Carl Siegel <carl.siegel@imagocenterdc.com>, johanri engelbrecht <johanri.engel@gmail.com>,
peter@relationships.co.nz, Carla DeFlorio <cdeflorio@imagorelationships.org>

However, when I pressed send, the names disappeared and the message did not send.

I tried sending in this format but still did not work

ckaravakis@imagorelationships.org, Slade.imago@icloud.com, iant241@gmail.com, carl.siegel@imagocenterdc.com, johanri.engel@gmail.com, peter@relationships.co.nz, cdeflorio@imagorelationships.org

**Comment by agilepro** [comment]
Apparently it was working correctly.  It transfers the names into the list of names at the bottom of the screen, however user did not see that, and thought that nothing was done.

Changed the page so that the composing panel closes (disappears) so you get a definite impression that something has been sent.   It also makes the list at the bottom much clearer.  There is a button to reopen and enter more names in if you wish.   This should address the problem.
