### ISSUE TITLE
gnarled up simultaneous typing

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#386]
Was typing at the same time in a closing round box with the other person. Our syntax got garbled. Should that be happening?

![image](https://user-images.githubusercontent.com/10082365/59120903-a1545f80-8924-11e9-945d-6fee296f032b.png)

**Comment by agilepro** [comment]
If you are typing in the same place at the same time, this is what happens.  Say you and I are both typing at the same place.   I type 111111111 and you type 222222222.   The synchronization happens every 15 seconds or so.     The result might be 1112211222211122122.    Because we are typig at the same time.   Here is what happened for you, split across two lines:

```
R         uss to set up agen              da for n   ext meeting
   set up                    next meeting          .
```

As you can see: every character was perfectly preserved, but when you type in exactly the same place at the same time, there is no way for the system to know that you did NOT intend this to be the result.   Does that make sense, or do you think there might be another way around this?
