### ISSUE TITLE
issue creating a new workspace

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#390]
See email I just sent about a problem Arvind (new user in India) is having trying to create a workspace

**Comment by agilepro** [comment]
First: there is little point in filing a GitHub issue without the issue details.  I did get the email and responded.  however weeks from now we would have no idea what the email was and the issue could not be tracked.

The issue is this screen shot:
![image](https://user-images.githubusercontent.com/5544889/60292015-0b7f7500-98d1-11e9-93bd-d24767a0e3c1.png)

As you can see, he set the name "EBHLE" for the workspace.  This is 5 letters.   The error says you need 6 or more letters.  If you can figure out how to make the message more clear, please let me know, but it seems pretty much exactly right.
