### ISSUE TITLE
can't delete email

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#400]
When I try to delete an old email address from my profile (the sociocracyconsulting.com address)  in the Weaver Board workspace, I get a rapid oscillation and see no removal when I bail out. Could be because the address I want to delete is my original system address?

![image](https://user-images.githubusercontent.com/10082365/61220444-575d5700-a6e4-11e9-9cf7-05791838c409.png)

**Comment by agilepro** [comment]
In short, you really don't want to do that.  You want to leave it there so that you have control over all the old records you created when logging in with that name.

You want to change your log-in email address.  You do that by doing the registration and setting a password.   And then, as long as you have both of these in there, you will have access to all the old things you did under the old address.    However, if you delete one, you might experience problems.

I am thinking I should get rid of the delete button, or at least add a warning to not use it unless you really know what you are doing.

**Comment by johnabuck** [comment]
it's causing me major problems. I can't log in as a user to most workspaces. I don't know how to undo what I did

**Comment by agilepro** [comment]
Add your email back to you profile

**Comment by agilepro** [comment]
Add your email back to you profile

**Comment by agilepro** [comment]
I have removed the button for deleting email.

Actually button is there, but it just shows a message saying to never delete old email addresses.
