### ISSUE TITLE
Converting agenda item of a meeting into a topic

### ISSUE THREAD

**Issue by kode7** [agilepro/cognoscenti#42]
While discussing a agenda item in a meeting it can come out that this topic cannot be finally handled in just one meeting. In this case it would be great to have a function that is converting the agenda item into a topic.

**Comment by agilepro** [comment]
Yes, excellent point.   I want to give Robert credit that his original design included this exact feature.  I have been too conservative in the implementation for one reason (and I am not sure it is a good one):  I worry that if you accidentally convert an agenda item to a topic, and all the comments/etc are moved there, it may be difficult to convert back.

Thinking about it now, this is not a problem with conversion of a single agenda item to a single topic, because it would not be difficult to convert back.  The problem was if you have a series of meetings with an agenda item "Foo" and convert the agenda item in the first to a Discussion topic.  Then on the second meeting, you attach the new discussion topic, and all the comments there are *merged* into those of the first.  Repeat.  Once merged, it is hard to un-merge them.   However, I think I am just being silly and overly cautious.  After writing it out here, it seems quite unlikely that this would be a big problem for anyone ......

**Comment by slatzel** [comment]
I know that merging is always hard to revert but the benefit from be able to revert is for me defenitly higher than the risk of reverting. In every software there are things you cannot undo without a lot of manual work. I think that's fine. People have to take care what they are doing.

**Comment by agilepro** [comment]
These are separate concepts now, and will remain separate
