### ISSUE TITLE
blank error message seems triggered by save command

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#424]
When I saved the first meeting, I again got the blank error message.

![image](https://user-images.githubusercontent.com/10082365/64834702-01f0d980-d5b1-11e9-8998-baaafd1a0004.png)

**Comment by agilepro** [comment]
This was caused by some file system glitch that confused Weaver into thinking there were two workspaces with the same name.  advanced-facilitation-class-fa and advanced-facilitation-class-fa-1.   Accessing one was sometimes accessing the other.  I removed the bogus duplicate workspace and all should be better now.

I will work to try and find the underlying bug that caused the two workspaces with the same name.  i have removed some code that might have caused it, though I don't know exactly what conditions caused it.
