### ISSUE TITLE
but also triggered by delete command

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#425]
The error message caused me to make multiple versions of the same meeting. I deleted the extras but got another blank error message. But when I renewed the page, then the delete had taken effect

![image](https://user-images.githubusercontent.com/10082365/64834853-af63ed00-d5b1-11e9-82fb-1f734de8a42f.png)

**Comment by agilepro** [comment]
This was caused by some file system glitch that confused Weaver into thinking there were two workspaces with the same name.  advanced-facilitation-class-fa and advanced-facilitation-class-fa-1.   Accessing one was sometimes accessing the other.  I removed the bogus duplicate workspace and all should be better now.

I will work to try and find the underlying bug that caused the two workspaces with the same name.  i have removed some code that might have caused it, though I don't know exactly what conditions caused it.
