### ISSUE TITLE
Am unable to create a new meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#426]
Can't add agenda items. The basic info I put in isn't saved. I just keep getting this page:

![image](https://user-images.githubusercontent.com/10082365/64834984-40d35f00-d5b2-11e9-9a1b-73644b8422ef.png)

**Comment by agilepro** [comment]
This was caused by some file system glitch that confused Weaver into thinking there were two workspaces with the same name.  advanced-facilitation-class-fa and advanced-facilitation-class-fa-1.   Accessing one was sometimes accessing the other.  I removed the bogus duplicate workspace and all should be better now.

I will work to try and find the underlying bug that caused the two workspaces with the same name.  i have removed some code that might have caused it, though I don't know exactly what conditions caused it.
