### ISSUE TITLE
Also unable to create topics

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#427]
I tried to create some topics but it wouldnt let me.

![image](https://user-images.githubusercontent.com/10082365/64836597-a9253f00-d5b8-11e9-884d-d9282d15b267.png)

**Comment by agilepro** [comment]
This was caused by some file system glitch that confused Weaver into thinking there were two workspaces with the same name.  advanced-facilitation-class-fa and advanced-facilitation-class-fa-1.   Accessing one was sometimes accessing the other.  I removed the bogus duplicate workspace and all should be better now.

I will work to try and find the underlying bug that caused the two workspaces with the same name.  i have removed some code that might have caused it, though I don't know exactly what conditions caused it.
