### ISSUE TITLE
problem with format

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#428]
Request we change the format of the way meeting agendas appear in email. I just got off the phone who was rather upset because of the message I sent out (excerpted below) about the upcoming online class. She looked at the display below and was upset that she was "just a participant and not one of those four people included in the target role." I suggest that the word "Participants" appear at the top of the list (not centered to the left). It also might be better to say simply "Role" rather than "Target Role" because "Target" is a word laden with lots of emotional connotations not intended by the specific Weaver context.

![image](https://user-images.githubusercontent.com/10082365/64922781-21e6ef80-d7a1-11e9-83d0-14280a997a5d.png)

**Comment by agilepro** [comment]
It took me a while to understand what was wrong.  The default behavior for web tables is to place the value centered vertically in the cell.

I suggest we get rid of Target Role (because that is an internal technical feature of the meeting that the organizer might wish to know, but is not important for attendees.)

I also will get rid of "state" because that will basically always be 1 (planning) when this sort of email is sent out.  

This format was originally just a "complete"dump of all the values, but I think it is removed by removing these things that participants (and facilitators) don't really need.

ALSO, make the label appear at the top of the cell, and not centered vertically.

**Comment by agilepro** [comment]
Target Role is now down below the participants, and lines between rows

![image](https://user-images.githubusercontent.com/5544889/71645399-adbb5380-2c8c-11ea-8ea1-53cb953b4461.png)
