### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#43]
I am setting up the Weaver Training workspace. I go into the Roles tab. I enter user's email addresses. Problems encountered:
1. I am only given the choice of entering user email. The email automatically becomes the player name also.
2. I go to the player's page. I change the player name. There is no back arrow to get out of this page. If I click tabs such as Settings, I get a 404 error. Only way out is to click Workspaces in the upper right corner.

**Comment by agilepro** [comment]
This was the "Unknown User" page that is displayed for email addresses which the owner has never logged in, and there is no profile.   This page had not been updated to the new UI look and feel, and had a dangling bad reference for sending invite.

Page is now updated, and I REMOVED the option to send an invite, because that invite needs to be on a particular site or workspace.  The Unknown User page does not have a site or workspace, so we can't send an invite from there.

Invite can be sent directly form the Role panel of a workspace
