### ISSUE TITLE
strange error messages

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#456]
User gets the following message (which I took off of her screen share) She was able to function despite the error message - but it would not go away from this screen

![image](https://user-images.githubusercontent.com/10082365/68595777-20b40500-0468-11ea-9543-761d50f326d0.png)

At one point this error message showed up - when she opened the edit window.

![image](https://user-images.githubusercontent.com/10082365/68596062-97510280-0468-11ea-8cfe-df778b119f4f.png)

**Comment by agilepro** [comment]
The first error message is because she was removed from the list of participants.  The list is empty, even though the meeting is completed.   I think someone accidentally removed everyone.   Actually, since all data values are empty, I suspect the problem is that she was logged out and no longer able to access the meeting information.   The second error message indicates the same thing.   This was network trouble related
