### ISSUE TITLE
Replying to reaction of a round

### ISSUE THREAD

**Issue by slatzel** [agilepro/cognoscenti#47]
It would be helpful to be able to reply to a reaction in a quick reaction round.

**Comment by agilepro** [comment]
Yes, that might be nice, but the design purposefully avoids that.  There is one proposal, and there is one response for each user.  Each user can edit their response as often as they want, but they have only one response.  They can edit their response to respond to any of the other people, but since there is only one response for every person, it will be easy for everyone to see the FINAL position of every person.  

If we allow open ended chains of responses, then it is hard to understand what a person's final position is.  

Comments allow infinite response.  But proposals are designed to have a single response for each person.
