### ISSUE TITLE
Meeting is displayed without recent changes when you use back button to return to it.

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#475]
I cloned meeting 3 in the Online Training On Sociocracy - Winter 2020 workspace to create meeting 4. I revised item 3 on that agenda and saved. When I returned to the item, I saw the save had not worked - had reverted to the previous form. Tried a couple of times and Save failed to work. I finally refreshed the page and saw that the save had worked. What is the time lag for updating saved changes?

**Comment by agilepro** [comment]
I have started working on a solution for this.  the problem is clicking the "back button".   Currently going back to a meeting presents the data in the exact form that the meeting had been when you originally fetched the page.   About 15 seconds later it is supposed to refresh, however when you return to a page the refresh does not seem to be happening.

**Comment by agilepro** [comment]
This is addressed.  The meeting used to get the initial display from the original page.  This is changed, and the current version of the meeting is fetched from the server when you return to it.
