### ISSUE TITLE
copy role

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#49]
There does not seem to be a way to edit the name of a role. To change the name of a role, the admin would have to completely recreate all of the role members' names and priveleges

**Comment by agilepro** [comment]
Thats right, the name is a key.

Roles should have a lot more attributes, particularly singleton roles.  It should say when the person was elected to the position, and it should have a reminder when it is time to elect someone else.   Etc.

**Comment by agilepro** [comment]
One can get the same functionality (without a deep change to the system) by adding a function to copy an existing role to a new name.  You can delete the old one if necessary.  Two steps instead of one, but renaming a role is a fairly rare thing, and a copy function is useful for more than just rename.

**Comment by agilepro** [comment]
implemented now!
