### ISSUE TITLE
more items from meeting with Forrist's group

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#492]
1. no opportuity to write cover message on emails of topic items remains a problem
2. in the Edit layout, order should be Subject, Description, Presenter, Notes/Minutes. In current layout description and minutes keep getting confused. 
3. ref an earlier issue item, I've figured out how I kept losing notes.  I was typing minutes by mistake in Description (see #2).  If there are two people in Description, whoever saves last wipes out the notes of the other person. 
4. The dual typing in the old format worked better. Now if two people are typing, the sentences get all mixed up. Really doesn't work to have two people in the box at the same time.
5. if you have a Round box set up in a topic, it populates with current members. What happens if someone else joins the workspace? Is there a way to add that person to the Round? Need to do that with Forrist's group because we want to keep a Round over time with people's backgrounds & new people will be coming in.
6. It would be helpful to have the ability to schedule two meeting reminders - not just one.

**Comment by agilepro** [comment]
I removed the "automatic" send of email.  Instead, you can press "Post and Send Email" and it will simply take you to the send email page where you can send an email normally, with a "cover" and it will appear in the list like all the others.

in the Edit layout, order should be Subject, Description, Presenter, Notes/Minutes. In current layout description and minutes keep getting confused.

I have changed this, but I am not convinced it is better.  "Getting confused" is simply a discord between what you think, and what exists.  We can change the what exists, or you can change what you think.  It is easy enough to change the order so I have done it.

The reason I put notes first is this:  When preparing the meeting, there are no notes and they take up no space.  The description will be dominant.   But after you start the meeting, you want (generally) to see the notes.  By having notes lower on the screen, you have to scroll down to them every time.  You have to scroll past the description which is no longer important.   By putting the important part first, you avoid having to scroll to get to the imporant part.   After the meeting starts the description is no longer important, so putting it at the top seems less efficient.

Like I say, mistakes happen when your concepts don't match the reality, and either can be changed.  The thing I value is that this input came from running a real meeting, and so I have changed the order.  Let me know how it works.

-----

Unfortunately it is a lot of work to make description dual-editable.  I could LOCK it so that description is not editable when the meeting is running.   That might be confusing as well.


The dual typing in the old format worked better. Now if two people are typing, the sentences get all mixed up. Really doesn't work to have two people in the box at the same time.


I have fixed these.   It will NOW turn orange when someone else makes a change, and a button to integrate the changes appears.   There is an "automatic merge" feature, but I don't recommend it because your cursor will jump around.

-----

if you have a Round box set up in a topic, it populates with current members. What happens if someone else joins the workspace? Is there a way to add that person to the Round? Need to do that with Forrist's group because we want to keep a Round over time with people's backgrounds & new people will be coming in.

------

You can just edit the list of responder:


![image](https://user-images.githubusercontent.com/5544889/79056564-a94bf280-7c0c-11ea-9eb6-2a4d4e43fd5d.png)






Just edit the round and add or remove responders.

----

It would be helpful to have the ability to schedule two meeting reminders - not just one.


Yes, that would be nice.


-Keith
