### ISSUE TITLE
registration process a bit confusing

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#513]
I have just finished orienting a new person to the IRW Stewards workspace. I had sent him an invitation to join the workspace. He said he didn't have a password so I asked him to screen share with me. 

There was a message in red saying that the password he'd been sent had expired. But I had just sent him the message. Since I was sending him the invitation for the first time, there was no way that he could already have a login, but the largest words in the message were instructing him to log in. Is there any way to have one message for invitations to people completely new to weaver and another for people who are already registered?

**Comment by agilepro** [comment]
"the password he'd been sent had expired"

The LINK was sent that would allow setting the password and I assume that is what you saw. The reason it was expired was because he has used it TWICE.   You may just have sent him one, however it is pretty clear that he used the OLD one instead.  It is hard to tell the difference.

By the way, passwords themselves never expire.  But the link to change the password does: in 7 days or after using it once. 

This is all about people new to Weaver.  You always get a link to reset your password, however there is another link to skip that and go straight to the workspace.
