### ISSUE TITLE
missing action item

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#53]
On my Front Page I see that I don't have any action items listed. However, I do have an active action item called "talk to other organization about using Weaver." It is tagged as Waiting Action Item. It would be helpful to tag such items to display on the Front Page so that I don't forget them.

**Comment by agilepro** [comment]
This is a really interesting point.  "Waiting" means that there are other actions that have to be done before this can be done.  The action item is waiting on other action items.  In this use, you don't want it to appear because you can't do anything with it.  When the other action item that it is waiting on is done, it will come back to the assigned state.

When it is assigned to you, and when you have accepted it, then it patiently waits for you (the assignee) to complete it.  You don't have to tell it to wait.

However, you saw it there, and chose to set it into "waiting".   This is a usability issue.  Will many people see that and put it into waiting?  Since the system does not know about any other task that will wake it back up, maybe the UI should not allow you to put it into waiting state.

OR, should there be better documentation of what "waiting" means?  How can this be done for users who do not read manuals?

**Comment by johnabuck** [comment]
I interpreted "waiting" not as waiting for something else but as "in
progress." Maybe that's what it needs to say?

On Mon, Jun 13, 2016 at 4:47 PM, Keith Swenson <notifications@github.com>
wrote:

> This is a really interesting point. "Waiting" means that there are other
> actions that have to be done before this can be done. The action item is
> waiting on other action items. In this use, you don't want it to appear
> because you can't do anything with it. When the other action item that it
> is waiting on is done, it will come back to the assigned state.
>
> When it is assigned to you, and when you have accepted it, then it
> patiently waits for you (the assignee) to complete it. You don't have to
> tell it to wait.
>
> However, you saw it there, and chose to set it into "waiting". This is a
> usability issue. Will many people see that and put it into waiting? Since
> the system does not know about any other task that will wake it back up,
> maybe the UI should not allow you to put it into waiting state.
>
> OR, should there be better documentation of what "waiting" means? How can
> this be done for users who do not read manuals?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/agilepro/cognoscenti/issues/53#issuecomment-225703424>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJnYPby528dwRTlQK8StJvpJK99q2KR-ks5qLcHUgaJpZM4IzsW8>
> .
>



-- 
John Buck
Certified Sociocracy Consultant
001-410-245-8654; skype: johnabuck

**Comment by iangilman** [comment]
It seems to me that the only way you should be able to mark an item as waiting on other action items is to explicitly connect it to those other items. Then when they complete it can automatically lose the "waiting" status.

That said, action item dependency is a pretty advanced feature. GitHub doesn't have it, and I suspect it's not because they haven't thought about it; it probably just causes more confusion than it helps. I'm not saying we should never do it, but maybe we don't need it for now at least.

**Comment by agilepro** [comment]
Removed Waiting, Reviewing, and Paused from the list of states that a person can select.  Waiting should be created automatically by the system when you create a subtask (this ability is currently hidden).   Reviewing is also automatic when you complete an action item that has valid reviewed (also hidden).  Finally paused is set by the system when the entire project is frozen, and not the sort of thing that a person would do individually.
