### ISSUE TITLE
won't take new player

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#545]
in the workgroup sociocracy>SSY 2020 Umesh tried to add the following email address to the list: vaisali.viswanathan@gmail.com.  However, once he pressed Return, the address disappeared At my suggestion, he tried to enter it through the invite user in the Options box, but even though he sent an invitation email, the name does not appear in the members role. 

I tried the same thing and encountered the same problem. Then, I tried entering my wife's name (it's a shorter email address) and that address was accepted with no problem.

**Comment by agilepro** [comment]
What was happening was that another existing user had that email address.  People can have multiple email addresses.  Somehow the user Shwetha had been set up with both the email address bailamozz@gmail.com and also with vaisali.viswathan@gmail.com.   Since it saw that you were adding the email address of a person already in the list, it eliminated it.   This is a feature to prevent you from adding the same user twice.   The user account looked like this:

![image](https://user-images.githubusercontent.com/5544889/100636787-efaea880-32e6-11eb-95b3-70664ff2c70f.png)

**Comment by agilepro** [comment]
I found this by going to the User List for the site, and trying to "create" a new user with the address vaisali.viswanathan@gmail.com and instead of creating one, it displayed the already existing entry fro Shwetha. Normally the old email addresses are real old email addresses for the person, and so there is no way to delete them.  The reason is that there might be an OLD OLD role that has them by the old email address.

I resolved the problem by creating a user with a bogus email address: vaisali.viswanathan2@gmail.com.   Then I ADD the correct email address to this user.  Adding an email address to a user will REMOVE it from all other users that might have it.  So that is a work-around if this ever happens again.

How did Shwetha end up with two email addresses?  The only way I know if to go to the user profile and ADD that address to the account.   It might have been the other way around.  There might have been a user account for vaisali.viswanathan@gmail.com which then for some reason got the Name of Shwetha, clearly the email address was wrong, so someone added her real email address to the profile, correcting the problem, but leaving the old email address in there.   There are no other ways that a user account can gain an email address.
