### ISSUE TITLE
names disappear

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#551]
When sending an email about a meeting, I enter the names from the Members list, edit out a few names, and then save and preview. When I then press send the email, the names have disappeared and have to be re-entered. Problem does not seem to occur if I select Regular Meeting Members and then add someone.

**Comment by agilepro** [comment]
Because you are creating a new email.  I don't see any way around this.   "Send Email" always creates a new email.  however, of you save without sending, it remains as a draft email.

I could make it look for an existing email that is composed and not sent.  BUT what if that email is about a different meeting? or not about any meeting at all?  i am not sure I can guarantee that whatever email is there would conform to what the user expects with choosing "Send Email"

Will have to think about this.

-Keith

**Comment by agilepro** [comment]
OK, I found and fixed a problem.  When you set the names of an email message that had a meeting associated, the email recipients was being replaced by the meeting participants WHEN being read.  So save works, and send works, but if you exit and reread the email the recipients get changed.

Remove the modification.  Now, if you want meeting participants, you have to use the add meeting participants, manually.
