### ISSUE TITLE
Many proposals with no conclusions

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#6]
The Weaver solution right now has produced a bunch of proposals that have no conclusions.  It's my understanding every proposal should find some sort of resolution, but we have a half-baked process in place at the moment that does not drive proposals to conclusions.  

I feel this is a bug of sorts - not in the code, but in the workflow process design.  I think we should use labels to distinguish code bugs from workflow process bugs here in GitHub.

**Comment by iangilman** [comment]
I don't think we should file GitHub issues that don't have clear action items...anything like that should just be a topic in Weaver. 

For this issue, I suppose the action items are:

* surface all of the unresolved proposals (e.g. in a page like the decision list and/or on home screens)
* provide a way to explicitly mark a proposal as abandoned (since not all proposals need lead to decisions)

**Comment by agilepro** [comment]
If these was a list of the proposals that YOU have created, that are past the dueDate, and have not been closed, would that take care of the problem?

**Comment by agilepro** [comment]
Weaver now has a list of all the rounds and proposals that you created, but have not closed.  The user need only check that list to find any overdue items that need closing.  The is no longer an excuse that "I forgot to complete the round or proposal".   When closing, you can create a decision or not, depending upon the result of the round.
