### ISSUE TITLE
what happened to this email message

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#602]
I sent a message from the Provisional World Childrens Parliament site on Sunday morning. I believe that I addressed Swarnalakshmi on the message. However, she has not received it. She checked in her Junk box and could not find it. Are my emails being blocked again?

Second problem: As the message system is set up now, it is not possible to verify who the addresses were. 

![image](https://user-images.githubusercontent.com/10082365/149791274-cd58989c-d5bc-4728-9730-4213a3593e20.png)

**Comment by agilepro** [comment]
I discovered yesterday that Hotmail is refusing email.

![image](https://user-images.githubusercontent.com/5544889/149864186-8839c0d2-6206-440f-a6b4-758f1d36f33e.png)



Here is the detail message from hotmail:




50 5.7.1 Unfortunately, messages from [149.72.32.175] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [DB5EUR03FT005.eop-EUR03.prod.protection.outlook.com]


So, I am at a loss.  Hotmail refuses the message.  What to do?  Get an email other than Hotmail?


-Keith

**Comment by agilepro** [comment]
no reply.  closing
