### ISSUE TITLE
cynthias test meeting

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#610]
meeting unfriendly - got this error.  right after it would not insert mhy name as presenter

<img width="855" alt="image" src="https://user-images.githubusercontent.com/10082365/156067841-23417e02-671c-47d0-8fb6-15eae73b1766.png">

**Comment by agilepro** [comment]
Problem was that the form was showing even when no agenda item showing, and in fact the meeting had no agenda items at all.  There was code to display only when an item was selected, but it didn't work.  Fixed so that the right side does not appear unless there is an agenda item selected.

![image](https://user-images.githubusercontent.com/5544889/156077508-ef8c6047-f0bc-4a81-adfc-2df2c8e6b4c5.png)
