### ISSUE TITLE
Unable to update profile icon

### ISSUE THREAD

**Issue by leilatite** [agilepro/cognoscenti#622]
There doesn't appear to be any way to update my profile page with an icon. This is confusing, since the system is inconsistent about what it uses to display my content. Sometimes it displays the first character of my user key (E), which was randomly generated and sometimes it displays the first letter of my name (L). The L seems to show up related to displaying emails.

**Comment by agilepro** [comment]
On the settings page, you should be able to click next to the (multiple) icons for you, and you should be able to upload a JPG file.

![image](https://user-images.githubusercontent.com/5544889/191790070-c553a803-ca2c-445c-8240-bf65fbf8fd6f.png)

**Comment by leilatite** [comment]
The browse and upload photo do not display for me - just the three icons.
![image](https://user-images.githubusercontent.com/3227429/191792157-616ffb8b-57ec-44a3-8bdb-04d993259d53.png)

**Comment by agilepro** [comment]
Click in the column where is says "Icon:"?   I believe it flashes purple when you hover over it.  This convention is used to indicate a place where you can click.  The column with the names is used with "single click" so that people with ipads and other touch devices can operate.   In many places (but not that one I just noticed) you can double-click on the data you want to change.

ALSO, I would like to generate unique icons for people.  Just not high enough on priority list.  I realized a few weeks ago that there are probably free services for generating icons, and it would be easy to integrate something like that.

**Comment by leilatite** [comment]
Thanks - that is working now. Maybe the help text that is displayed when you click on the question mark could include those instructions.

**Comment by agilepro** [comment]
I added text into the help message.
