### ISSUE TITLE
Meeting times should be shown in user's timezone, not Pacific time

### ISSUE THREAD

**Issue by leilatite** [agilepro/cognoscenti#624]
The times shown when planning a meeting are correct for my timezone. When I look at the agenda, it shows PDT.
![image](https://user-images.githubusercontent.com/3227429/191854389-e4e28c24-c8a6-473c-8fa8-e34b4e11c911.png)

Planning view shows times in my timezone
![image](https://user-images.githubusercontent.com/3227429/191854592-b35882db-5fcf-4b58-9076-d0915e702d5b.png)

Running should also show in user's timezone. I will confirm later today as I try running the meeting.

**Comment by agilepro** [comment]
This is actually functioning correctly although it might be confusing.

You have a setting for timezone that is used when email is sent because we don't otherwise know what timezone you will be receiving the email in.  This same timezone is used for the agenda/minutes because that is generated on the server using the same mechanism that the email is generated with.

The rest of the pages use the timezone of your browser because they are **interactive** web pages and we know what time zone you are currently in.

The thing is, your account is set to Los Angeles time.  Set it to your time zone.

![image](https://user-images.githubusercontent.com/5544889/191891802-ff4d673d-c532-411f-9cee-e59a6f6822c6.png)

Furthermore, you probably see a warning if this is set differently from your browser, something like this:

![image](https://user-images.githubusercontent.com/5544889/191892010-413b1d96-c7a6-4d8b-99a5-a93ccf452961.png)
