### ISSUE TITLE
unclear about generating meeting minutes

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#77]
If I generate minutes from the sync meeting agenda, it shows up as a draft in topics. I have to then go to topics and make a selection (like "freeform") from a dropdown list - none of which really have anything to do with generating minutes. Request is for process to be less convoluted.

**Comment by agilepro** [comment]
Here is how I use it:

The "generation" of the meeting minutes is imperfect because it is taken from the record of the meeting.  Descriptions and 'minutes' entries are include.  The description of  a meeting has information that is useful for joining the meeting, but not useful for after the meeting.  The idea is that you generate the minutes, _edit them_, and then publish them.

The minutes are not sent as email until they are published (taken out of draft mode).  The reason it starts in draft mode is to give you time to edit and correct the minutes BEFORE they are sent as email.  i kept having the problem that they would be instantly sent as email before I got a chance to fix all the issues.

It is nice to think that the minutes are blow-by-blow record of what happened at the meeting, but that is not always right.  The minutes are best viewed as a story that tells you what happened.  Much of the detail of a meeting is unfit for the minutes -- the entire discussion of a topic will often take detours which are resolved, and best not mentioned in the minutes.  Ultimately, you want the minutes to tell concisely what is important about the results of the meeting.  It is very difficult to take notes during a meeting that perfectly transform into good minutes at the end.

So the compromise:  take notes as best you can, but ALLOW the minutes to be edited in order to make them consistent and concise.  That needs to be done before the email is sent, so you need a draft mode.

There is another approach, and that is to "virtually generate" the minutes.  This would be a representation of the meeting that comes directly from the meeting structure.  There would be a button to "view" the minutes, and if you need to edit them, instead of directly editing the minutes, you would edit the objects underneath.  This will be confusing to many people, because they will not be able to change things that are part of the structure of the meeting.  Say, for instance, that several agenda items were not discussed from the agenda -- you might want to completely remove all mention since it was caused simply by inadequate planning, and there is no reason to blast all over the place that kind of detail.  Say an emergency agenda item was included, discussed.  When you minutes are directly tied to the meeting structure, you would need to add this agenda item to the agenda after the meeting ended in order to make the results appear in the minutes, but in a sense that agenda item was not on the agenda that was distributed before the meeting.    It is far far easier to just give the entire minutes to the user to edit directly -- then all aspects of the minutes can be adjusted to fit the style and needs of the organization.

**Comment by agilepro** [comment]
I could add a button on the meeting that says "publish the minutes as they are" when the minutes are in draft mode.

**Comment by agilepro** [comment]
I address this with these changes:

1) When you generate, it generates as draft, and the page clearly says "Draft minutes"

2) The button says "View Minutes"

3) While in draft mode, a second button appear saying "Post Minutes as they are"  Press this button put the minutes in Freeform mode, which will cause the email to be sent

4) When not in draft mode, the prompt says "Posted Minutes"

It stil means you have to make a couple of clicks, but hopefully it is clear now exactly what the current situation is, and it is easy to access buttons that change the situation without a lot of convolution.
