### ISSUE TITLE
No timers on workflow process steps

### ISSUE THREAD

**Issue by goodgeyes** [agilepro/cognoscenti#8]
Much of the present solution does not work adequately because these do not yet exist.  We need to redesign our solution with countdown timers.

I recommend a solution with a workflow process that has timers at every step - including when a human facilitator jumps into the flow.

The actual time intervals should be defined by each group and constrained by the org.  But it is quite important that there not be too many different time intervals, so everyone quickly learns how much time they have to engage at each step.

Before we can start thinking about appropriate time intervals we need to lay out all the steps in the workflow from idea conception to final decision text being logged in the database.  There are lots of steps in between.  Some optional steps and steps that will need many iterations in some proposal cases.

**Comment by iangilman** [comment]
So, action item: 

* Add timers to proposals with some sort of automatic action (becomes a decision if no objections? Otherwise becomes abandoned?) for when they time out.

**Comment by agilepro** [comment]
So we have timers already.
- Proposals and Rounds have duedates which count down to that time.
- Action items have a duedate which counts down as well

What we don't have, is a feature that reaches out of the computer and forces people to respond.  That is, there are no consequences to allowing the timer run out.  I am goingn to close this because it only talks about the timers, which actually exist.  Please create another about what the consequences of a timer expiration should be.
