### ISSUE TITLE
Do we need Draft topic?  Can we have more "phases" to start in?

### ISSUE THREAD

**Issue by johnabuck** [agilepro/cognoscenti#91]
When I create a topic, I am offered three options for phase: Freeform, Draft Topic, and Picture Forming. I don't know what "Draft Topic" means, and I need more sociocracy options. 

Can "Draft Topic" be removed?

Seems like the options should be: Freeform, Picture Forming, Proposal Shaping, Proposal (or Proposal Finalizing). (You can start at any point in the sociocracy decision making process.) 

Or maybe the only option should be "Draft Topic" in case you're not ready to publish it. Then you can simply use the categories provided in the pull down box that appears on the left side when the topic is actually opened.

**Comment by agilepro** [comment]
The purpose of "Draft" is because you want to get the topic into a suitable mode BEFORE the email is sent.  You might be able to type the entire topic on one go, or you might find you need to save things before you are finished.  This serves the same as draft email:  you didn't have time to write the whole email in on go, and you need to save your partial work so you can get back to it.

How would you tell if someone (the user) was "ready to publish"?  Draft should indeed be the default mode when you create something.  It stays in draft until you decide it should be in either Free form or Picture forming.   If you want more than this, it is easy, but which ones?

**Comment by agilepro** [comment]
topic modes have improved significantly.
